CUSTOMER_ID=phosfe
APP_NAME=Phosfe TechPOS
APPLICATION_ID=com.phosfe.bkmtechpos
ARTIFACT_NAME=PhosfeTechPOS
VERSION_CODE=1
VERSION_NAME=1.0.0

# These values must be replaced with the identifiers assigned to this customer by BKM.
PRODUCER_CODE=
DEVICE_TYPE=
SERIAL_HEADER=
DAKT=false
PRINTER_PRESENT=true
